name: Build IS with Changes

on:
  push:
      branches:
        - '**'
  workflow_dispatch:
    inputs:
      kernel-branch:
        description: 'Branch for Carbon Kernel'
        required: true
        default: 'unify-httpclient'
      framework-branch:
        description: 'Branch for Identity Framework'
        required: true
        default: 'v7.8.23-http-client'
      governance-branch:
        description: 'Branch for Identity Governance'
        required: true
        default: 'http-client'
      current-branch:
        description: 'Branch for Identity Server'
        required: true
        default: 'build_is'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      
      # Repository 1
      - name: Checkout Carbon Kernel
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-kernel'
          ref: ${{ github.event.inputs.kernel-branch || 'unify-httpclient' }}
          path: './carbon-kernel'
      
      - name: Build Carbon Kernel
        run: |
          cd ./carbon-kernel
          mvn clean install -Dmaven.test.skip=true
      
      # Repository 2
      - name: Checkout Identity Framework
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-identity-framework'
          ref: ${{ github.event.inputs.framework-branch || 'v7.8.23-http-client' }}
          path: './identity-framework'
      
      - name: Build Identity Framework
        run: |
          cd ./identity-framework
          mvn clean install -Dmaven.test.skip=true
      
      # Repository 3
      - name: Checkout Identity Governance
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-identity-governance'
          ref: ${{ github.event.inputs.governance-branch || 'http-client' }}
          path: './identity-governance'
      
      - name: Build Identity Governance
        run: |
          cd ./identity-governance
          mvn clean install -Dmaven.test.skip=true
      
      # Current Repository (wso2-identity-server)
      - name: Checkout Current Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.current-branch || github.ref_name }}
          path: './wso2-identity-server'
      
      - name: Build Current Repository
        run: |
          cd ./wso2-identity-server
          mvn clean install
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./wso2-identity-server/modules/*/target/*.jar
            ./wso2-identity-server/target/*.jar
