name: Sequential Dependency Build

on:
  workflow_dispatch:
    inputs:
      kernel-branch:
        description: 'Branch for Carbon Kernel'
        required: true
        default: 'unify-httpclient'
      framework-branch:
        description: 'Branch for Identity Framework'
        required: true
        default: 'v7.8.23-http-client'
      governance-branch:
        description: 'Branch for Identity Governance'
        required: true
        default: 'http-client'
      current-branch:
        description: 'Branch for Identity Server'
        required: true
        default: 'build_is'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      
      # Repository 1
      - name: Checkout Carbon Kernel
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-kernel'
          ref: ${{ github.event.inputs.kernel-branch }}
          path: './carbon_kernel'
      
      - name: Build Carbon Kernel
        run: |
          cd carbon_kernel
          mvn clean install -Dmaven.test.skip=true
          cd ..
      
      # Repository 2
      - name: Checkout Identity Framework
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-identity-framework'
          ref: ${{ github.event.inputs.framework-branch }}
          path: './framework'
      
      - name: Build Identity Framework
        run: |
          cd framework
          mvn clean install -Dmaven.test.skip=true
          cd ..
      
      # Repository 3
      - name: Checkout Identity Governance
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-identity-governance'
          ref: ${{ github.event.inputs.governance-branch }}
          path: './governance'
      
      - name: Build Identity Governance
        run: |
          cd governance
          mvn clean install -Dmaven.test.skip=true
          cd ..
      
      # Current Repository (wso2-identity-server)
      - name: Checkout Current Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.current-branch }}
          path: './current'
      
      - name: Build Current Repository
        run: |
          cd current
          mvn clean install
