name: Build IS with BouncyCastle

on:
  push:
      branches:
        - '**'
  workflow_dispatch:
    inputs:
      kernel-branch:
        description: 'Branch for Carbon Kernel'
        required: true
        default: 'v4.10.48-bouncycastle'
      current-branch:
        description: 'Branch for Identity Server'
        required: true
        default: 'v7.2.0-m2-bouncycastle'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # First checkout the current repository as a base
      - name: Checkout Current Repository First
        uses: actions/checkout@v3
        
      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      
      # Repository 1
      - name: Checkout Carbon Kernel
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-kernel'
          ref: ${{ github.event.inputs.kernel-branch || 'v4.10.48-bouncycastle' }}
          path: './carbon-kernel'
          
      - name: Verify Carbon Kernel Checkout
        run: |
          echo "Listing files in carbon-kernel directory:"
          ls -la ./carbon-kernel
          echo "Checking for pom.xml:"
          find ./carbon-kernel -name "pom.xml" | head -n 5
      
      - name: Build Carbon Kernel
        run: |
          if [ -f "./carbon-kernel/pom.xml" ]; then
            cd ./carbon-kernel
            mvn clean install -Dmaven.test.skip=true
          else
            echo "ERROR: No pom.xml found in Carbon Kernel directory"
            exit 1
          fi
      
      # Current Repository (wso2-identity-server)
      - name: Checkout Current Repository Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.current-branch || 'v7.2.0-m2-bouncycastle' }}
          
      - name: Verify Current Repository Checkout
        run: |
          echo "Listing files in current directory:"
          ls -la
          echo "Checking for pom.xml:"
          find . -maxdepth 1 -name "pom.xml"
      
      - name: Build Current Repository
        run: |
          if [ -f "pom.xml" ]; then
            mvn clean install
          else
            echo "ERROR: No pom.xml found in Current Repository directory"
            exit 1
          fi
