name: Build IS with Changes

on:
  push:
      branches:
        - '**'
  workflow_dispatch:
    inputs:
      kernel-branch:
        description: 'Branch for Carbon Kernel'
        required: true
        default: 'unify-httpclient'
      framework-branch:
        description: 'Branch for Identity Framework'
        required: true
        default: 'v7.8.23-http-client'
      governance-branch:
        description: 'Branch for Identity Governance'
        required: true
        default: 'http-client'
      current-branch:
        description: 'Branch for Identity Server'
        required: true
        default: 'build_is'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # First checkout the current repository as a base
      - name: Checkout Current Repository First
        uses: actions/checkout@v3
        
      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      
      # Repository 1
      - name: Checkout Carbon Kernel
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-kernel'
          ref: ${{ github.event.inputs.kernel-branch || 'unify-httpclient' }}
          path: './carbon-kernel'
          
      - name: Verify Carbon Kernel Checkout
        run: |
          echo "Listing files in carbon-kernel directory:"
          ls -la ./carbon-kernel
          echo "Checking for pom.xml:"
          find ./carbon-kernel -name "pom.xml" | head -n 5
      
      - name: Build Carbon Kernel
        run: |
          if [ -f "./carbon-kernel/pom.xml" ]; then
            cd ./carbon-kernel
            mvn clean install -Dmaven.test.skip=true
          else
            echo "ERROR: No pom.xml found in Carbon Kernel directory"
            exit 1
          fi
      
      # Repository 2
      - name: Checkout Identity Framework
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-carbon-identity-framework'
          ref: ${{ github.event.inputs.framework-branch || 'v7.8.23-http-client' }}
          path: './identity-framework'
          
      - name: Verify Identity Framework Checkout
        run: |
          echo "Listing files in identity-framework directory:"
          ls -la ./identity-framework
          echo "Checking for pom.xml:"
          find ./identity-framework -name "pom.xml" | head -n 5
      
      - name: Build Identity Framework
        run: |
          if [ -f "./identity-framework/pom.xml" ]; then
            cd ./identity-framework
            mvn clean install -Dmaven.test.skip=true
          else
            echo "ERROR: No pom.xml found in Identity Framework directory"
            exit 1
          fi
      
      # Repository 3
      - name: Checkout Identity Governance
        uses: actions/checkout@v3
        with:
          repository: 'linukaratnayake/wso2-identity-governance'
          ref: ${{ github.event.inputs.governance-branch || 'http-client' }}
          path: './identity-governance'
          
      - name: Verify Identity Governance Checkout
        run: |
          echo "Listing files in identity-governance directory:"
          ls -la ./identity-governance
          echo "Checking for pom.xml:"
          find ./identity-governance -name "pom.xml" | head -n 5
      
      - name: Build Identity Governance
        run: |
          if [ -f "./identity-governance/pom.xml" ]; then
            cd ./identity-governance
            mvn clean install -Dmaven.test.skip=true
          else
            echo "ERROR: No pom.xml found in Identity Governance directory"
            exit 1
          fi
      
      # Current Repository (wso2-identity-server)
      - name: Checkout Current Repository Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.current-branch || github.ref_name }}
          
      - name: Verify Current Repository Checkout
        run: |
          echo "Listing files in current directory:"
          ls -la
          echo "Checking for pom.xml:"
          find . -maxdepth 1 -name "pom.xml"
      
      - name: Build Current Repository
        run: |
          if [ -f "pom.xml" ]; then
            mvn clean install
          else
            echo "ERROR: No pom.xml found in Current Repository directory"
            exit 1
          fi
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./modules/*/target/*.jar
            ./target/*.jar
